/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ChatPopover: typeof import('./src/components/chat-popover.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClientPopover: typeof import('./src/components/client-popover.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Message: typeof import('primevue/message')['default']
    MeterGroup: typeof import('primevue/metergroup')['default']
    NewTunnelDrawer: typeof import('./src/components/new-tunnel-drawer.vue')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    SettingsCard: typeof import('./src/components/settings-card.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TunnelDrawer: typeof import('./src/components/new-tunnel-drawer.vue')['default']
    UserPopover: typeof import('./src/components/user-popover.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
